PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name" :"Steve Urkel",
    "description": "Urkel time",
    "location":"Urkel house",
    "dateTime":"2024-01-01T15:30:00.000Z"
}